// Generated by LiveScript 1.2.0
var global, obj;
function Obj(data){
  console.log(this);
  this.data = data;
  console.log(this);
}
global = {
  map: [],
  get: function(){
    return global.map[0];
  }
};
obj = new Obj('hey ! i am an object.');
global.map.push(obj);
global.map[0] = null;
obj = null;
global = null;